# Copyright 2017 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# -----------------------------------------------------------------------------

version: "2.1"

services:

# Copyright 2017 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------------

version: '2.1'

services:
  market-rest-api-env:
    build:
      context: ../../
      dockerfile: ./integration_tests/rest_api/Dockerfile
    image: market-rest-api-test-env
    depends_on:
      - market-rest-api
      - market-ledger-sync
      - market-processor
    volumes:
      - '../../:/project/sawtooth-marketplace'
    environment:
      PYTHONPATH: /project/sawtooth-marketplace/addressing
    command: |
      dredd ./rest_api/api-spec.yaml http://market-rest-api:8040
        --reporter=dot

  market-processor:
    build:
      context: ../../
      dockerfile: ./processor/Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: market-tp
    volumes:
      - '../../:/project/sawtooth-marketplace'
    command: echo "No transaction processor command set"

  market-rest-api:
    build:
      context: ../../
      dockerfile: ./rest_api/Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: market-rest-api
    volumes:
      - ../../:/project/sawtooth-marketplace
    depends_on:
      - market-ledger-sync
      - rethink
      - validator
    command: echo "No REST API command set"

  market-ledger-sync:
    build:
      context: ../../
      dockerfile: ./ledger_sync/Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: market-ledger-sync
    volumes:
      - ../../:/project/sawtooth-marketplace
    depends_on:
      - rethink
      - validator
    command: echo "No ledger sync command set"

  rethink:
    image: rethinkdb:2.3
    expose:
      - 8080
      - 28015

  settings-tp:
    image: hyperledger/sawtooth-settings-tp:1.0
    depends_on:
      - validator
    command: settings-tp -vv --connect tcp://validator:4004

  validator:
    image: hyperledger/sawtooth-validator:1.0
    expose:
      - 4004
    command: |
      bash -c "
        sawadm keygen && \
        sawtooth keygen my_key && \
        sawset genesis -k /root/.sawtooth/keys/my_key.priv && \
        sawadm genesis config-genesis.batch && \
        sawtooth-validator -vv \
          --endpoint tcp://validator:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800
      "
