# Copyright 2017 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------------

version: '2.1'

services:
  processor:
    build:
      context: .
      dockerfile: ./processor/Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: marketplace-tp
    volumes:
      - '.:/project/sawtooth-marketplace'
    command: echo "No transaction processor command set"

  rest-api:
    build:
      context: .
      dockerfile: ./rest_api/Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: marketplace-rest-api
    volumes:
      - .:/project/sawtooth-marketplace
    ports:
      - '8000:8000'
    depends_on:
      - ledger-sync
      - rethink
      - validator
    command: echo "No REST API command set"

  ledger-sync:
    build:
      context: .
      dockerfile: ./ledger_sync/Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: marketplace-ledger-sync
    volumes:
      - .:/project/sawtooth-marketplace
    depends_on:
      - rethink
      - validator
    command: echo "No ledger sync command set"

  rethink:
    image: rethinkdb:2.3
    expose:
      - 8080
      - 28015
    ports:
      - '9090:8080'
      - '29015:28015'

  sawtooth-rest-api:
    image: hyperledger/sawtooth-rest-api:1.0
    container_name: sawtooth-rest-api
    expose:
      - 8008
    ports:
      - '8008:8008'
    depends_on:
      - validator
    entrypoint: sawtooth-rest-api --connect tcp://validator:4004 --bind sawtooth-rest-api:8008 -vv

  shell:
    image: hyperledger/sawtooth-shell:1.0
    volumes:
      - '.:/project/sawtooth-marketplace'
    working_dir: /project/sawtooth-marketplace
    container_name: sawtooth-shell
    depends_on:
      - rest-api
    entrypoint: |
      bash -c "
        sawtooth keygen &&
        tail -f /dev/null
      "
  settings-tp:
    image: hyperledger/sawtooth-settings-tp:1.0
    depends_on:
      - validator
    command: settings-tp -vv --connect tcp://validator:4004

  validator:
    image: hyperledger/sawtooth-validator:1.0
    expose:
      - 4004
    ports:
      - '4004:4004'
    command: |
      bash -c "
        sawadm keygen && \
        sawtooth keygen my_key && \
        sawset genesis -k /root/.sawtooth/keys/my_key.priv && \
        sawadm genesis config-genesis.batch && \
        sawtooth-validator -vv \
          --endpoint tcp://validator:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800
      "
